version: '3.8'

services:
  build:
    working_dir: /cumulus-dashboard
    image: dashboard-build:${TAG-}
    platform: linux/amd64
    build:
      dockerfile: docker/Dockerfile
      context: ../
      target: build
      args:
        - APIROOT
        - AUTH_METHOD
        - AWS_REGION
        - DAAC_NAME
        - ENABLE_RECOVERY
        - HIDE_PDR
        - KIBANAROOT
        - SERVED_BY_CUMULUS_API
        - STAGE
        - DOCKER_DEFAULT_PLATFORM
  dashboard:
    working_dir: /cumulus-dashboard
    image: ${IMAGE_NAME}
    platform: linux/amd64
    build:
      dockerfile: docker/Dockerfile
      context: ../
      args:
        - APIROOT
        - AUTH_METHOD
        - AWS_REGION
        - DAAC_NAME
        - ENABLE_RECOVERY
        - HIDE_PDR
        - KIBANAROOT
        - SERVED_BY_CUMULUS_API
        - STAGE
        - DOCKER_DEFAULT_PLATFORM
