version: "3"
services:
  elasticsearch:
    image: ${DOCKER_REPOSITORY}elasticsearch:5.3
    network_mode: "service:shim"
    environment:
      ES_JAVA_OPTS: "-Xms750m -Xmx750m"
  localstack:
    image: ${DOCKER_REPOSITORY}localstack/localstack:0.12.13
    network_mode: "service:shim"
    environment:
      SERVICES: "cloudformation,cloudwatch,cloudwatchlogs,dynamodb,iam,kinesis,kms,lambda,s3,secretsmanager,sns,sqs,stepfunctions,ssm,logs"
  shim:   # empty container to open ports
    image: ${DOCKER_REPOSITORY}node:14.19.1
    command:
      bash -c "tail -f /dev/null"
    working_dir:
      /cumulus-dashboard
    volumes:
      - ../:/cumulus-dashboard
    ports:
      - "9200:9200"
      - "4550-4599:4550-4599"
      - "5432:5432"
  postgres:
    image: postgres:10.17-alpine
    network_mode: "service:shim"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "postgres"
